#!/usr/bin/env bash

TIMER=600
source /home/gyr/.gyr.d/suse.d/bin/.env
REPOSITORY=images

function usage() {
    printf "Usage: %s [-a api_url] -p project [-r repository] [-t timer]\n" $(basename $0)
}

while getopts "a:p:r:t:" opt; do
    case $opt in
        a)
            API_URL=${OPTARG}
            ;;
        p)
            PROJECT=${OPTARG}
            ;;
        r)
            REPOSITORY=${OPTARG}
            ;;
        t)
            TIMER=${OPTARG}
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [ -z "${PROJECT}" ] ; then
    usage
    exit 1
fi

while (osc -A ${API_URL} api "/build/${PROJECT}/_result?view=summary&repository=${REPOSITORY}" | grep "result project" | grep -v 'code="published" state="published">'); do
    echo PENDING
    sleep ${TIMER}
done

osc -A ${API_URL} api "/build/${PROJECT}/_result?view=summary&repository=${REPOSITORY}" | grep "result project" | grep 'code="published" state="published">' && echo PUBLISHED
