#!/usr/bin/env sh

APIURL='https://api.suse.de/'

function usage() {
    printf "Usage: %s [-a api_url] -p project [-t days]\n" $(basename $0)
}

while getopts "a:p:t:" opt; do
    case $opt in
        a)
            APIURL=${OPTARG}
            ;;
        p)
            PROJECT=$OPTARG
            ;;
        t)
            TIME_RANGE="-D $OPTARG"
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [ -z "${PROJECT}" ] ; then
    usage
    exit 1
fi


ex <(osc -A ${APIURL} request list -t submit ${TIME_RANGE} -s accepted ${PROJECT}) << EOF
# cleanup input
v/^[[:digit:]]\|submit:/d
# join lines 2 by 2
g/./j
# format output: {timestamp} {package_name} https://build.suse.de/request/show/{request_id}
%s;\(^[[:digit:]]*\) .*When:\(.*[[:digit:]]\).*submit:.*/\(.*\)@.*;\2 \3 https://build.suse.de/request/show/\1;
# sort output by timestamp
%!sort
0i
==============================
SUBMIT REQUESTS
==============================
.
%p
q!
EOF

ex <(osc -A ${APIURL} request list -t delete ${TIME_RANGE} -s accepted ${PROJECT}) << EOF
# cleanup input
v/^[[:digit:]]\|delete:/d
# join lines 2 by 2
g/./j
# format output: {timestamp} {package_name} https://build.suse.de/request/show/{request_id}
%s;\(^[[:digit:]]*\) .*When:\(.*[[:digit:]]\).*delete:.*/\(.*\);\2 \3 https://build.suse.de/request/show/\1;
# sort output by timestamp
%!sort
0i
==============================
DELETE REQUESTS
==============================
.
%p
q!
EOF
