#!/usr/bin/env sh

APIURL='https://api.suse.de/'

function usage() {
    printf "Usage: %s [-a api_url] -p project [-t days]\n" $(basename $0)
}

while getopts "a:p:t:" opt; do
    case $opt in
        a)
            APIURL=${OPTARG}
            ;;
        p)
            PROJECT=$OPTARG
            ;;
        t)
            TIME_RANGE="-D $OPTARG"
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [ -z "${PROJECT}" ] ; then
    usage
    exit 1
fi

echo "=============================="
echo "SUBMIT REQUESTS"
echo "=============================="

osc -A ${APIURL} request list -t submit ${TIME_RANGE} -s accepted ${PROJECT} | \
    grep -A 1 "^[0-9]" | \
    sed \
        -e '/^--$/d' \
        -e '$!N;s/\n/ /' | \
    grep "***make origin older***" | \
    sed -e 's;^\([[:digit:]]*\)  .*When:\(.*[[:digit:]]\).*submit:.*\/\(.*\) ->.*;\2 \3 https://build.suse.de/request/show/\1;' \
        -e 's/@.* / /' | \
    sort | \
    sed -e 's/^\(.*\) \(.*\) \(https.*\)/\2 (\1) \3/'
 # filter request id and package name lines
 # delete separators
 # merge lines
 # filter request to Project not from Project
 # filter date, package name and create SR URL
 # sort
 # move package name to the beginning of the line

echo "=============================="
echo "DELETE REQUESTS"
echo "=============================="

osc -A ${APIURL} request list -t delete ${TIME_RANGE} -s accepted ${PROJECT} | \
    grep -A 1 "^[0-9]" | \
    sed \
        -e 's/^[[:space:]].*\/\(.*\)/\1/' \
        -e 's;^\([[:digit:]]*\)  .*When:\(.*\);\2 https://build.suse.de/request/show/\1;' \
        -e 's/^[[:space:]]*//' \
        -e '/^--$/d' | \
    sed -e '$!N;s/\n/ /' | \
    sort | \
    sed -e 's/^\(.*\)[[:space:]]\(https.*\)[[:space:]]\(.*\)/\3 (\1) \2/'

 # swap lines
