#!/usr/bin/env sh

IBS_DIR="${HOME}/ibs"
PKG_GRP_DIR="${IBS_DIR}/home:gyribeiro:branches:SUSE:SLE-15-SP2:GA/000package-groups"

if [ -d ${IBS_DIR} ]; then
    if [ -d ${PKG_GRP_DIR} ]; then
       rm -rvf ${PKG_GRP_DIR}
    fi
else
   mkdir -vp ${IBS_DIR}
fi

cd ${IBS_DIR}
osc -A https://api.suse.de/ bco SUSE:SLE-15-SP2:GA 000package-groups
echo "cd ${PKG_GRP_DIR}"
