#!/bin/sh
VERSION=$1
CODESTREAM=$(echo $1 | sed -e 's/-.*//g')

sle_15_media_build() {
    PROJECT=$1
    echo "builds from $PROJECT:"
    for i in $(osc -A https://api.suse.de/ api "/build/$PROJECT/_result?package=000product&multibuild=1&repository=images&arch=local&view=binarylist"  | grep "binary filename" | grep "DVD\|cd-cd\|Packages\|Full\|Online" | grep "Media1.iso\"" | sed -e 's/\(.*\)filename="\(.*.iso\).*/\2/g' | grep x86_64) ; do
        echo $i | sed -e 's/-x86_64-/:\t\t/g;s/-Media.*iso//;s/-Packages-x86_64-/-Packages:\t\t/g' | sed -e 's/^[[:space:]]*//'
    done
}

sle_images() {
    PROJECT=$1
    echo "images from $PROJECT:"

    TEMP_FILE="$(mktemp)"

    KIWI_TEMPLATE=$(osc -A https://api.suse.de ls  $PROJECT | grep kiwi-templates );
    if [ "$KIWI_TEMPLATE" != "" ]; then
        # multibuild JeOS
        for i in $(osc -A https://api.suse.de cat  $PROJECT $KIWI_TEMPLATE _multibuild | grep flavor | sed -e 's,.*<flavor>,,g;s,</.*,,g') ; do
            osc -A https://api.suse.de ls -b  $PROJECT $KIWI_TEMPLATE:$i images | grep '.packages$' | sed -e 's/\.packages//' | sed -e 's/^[[:space:]]*//' >> $TEMP_FILE &
        done
    fi

    # Multibuild images such as cloud etc, typical name is SLE12-SP5-EC2
    # This is for 15.2+ and 12.5+
    for package in $(osc -A https://api.suse.de ls "$PROJECT" | grep "^SLE" | grep -v release); do
        for flavor in $(osc -A https://api.suse.de cat $PROJECT/$package/_multibuild | grep flavor); do
            osc -A https://api.suse.de ls -b $PROJECT $package:$(echo $flavor | sed -E "s/<(\/)?flavor>//g")/images | grep packages | sed "s/.packages//" | sed -e 's/^[[:space:]]*//' >> $TEMP_FILE &
        done 2> /dev/null
    done

    # old style
    for i in $(osc -A https://api.suse.de ls $PROJECT | grep -v _product | grep -v 000product | grep -v kiwi ); do
        osc -A https://api.suse.de ls -b  $PROJECT $i images | grep '.packages$' | sed -e 's/\.packages//' | sed -e 's/^[[:space:]]*//'  >> $TEMP_FILE &
    done
    wait
    sort $TEMP_FILE
    rm $TEMP_FILE
}


if [ "$CODESTREAM" == "15" ]; then
    sle_15_media_build SUSE:SLE-$VERSION:GA
    echo
    sle_15_media_build SUSE:SLE-$VERSION:GA:TEST
    echo
    sle_15_media_build SUSE:SLE-$VERSION:GA:PUBLISH
    echo
    sle_images SUSE:SLE-$VERSION:GA:TEST
    echo
    sle_images SUSE:SLE-$VERSION:GA:PUBLISH
else
    echo "builds from SUSE:SLE-$VERSION:GA:"
    for i in  $(osc -A https://api.suse.de/ ls SUSE:SLE-$VERSION:GA | grep _product | grep 'DVD-x86\|cd-cd.*x86_64' ) ; do
        osc -A https://api.suse.de/ ls -b SUSE:SLE-$VERSION:GA $i images local | grep 'Media1.iso$\|Media.iso$' | sed -e 's/-DVD-.*x86_64-/:\t\t/g;s/-Media.*iso//' | sed -e 's/^[[:space:]]*//' &
    done
    sle_images SUSE:SLE-$VERSION:GA:TEST
fi


# WSL
# avoid displaying images-test/$arch
echo
echo "WSL image (from SUSE:SLE-$VERSION:Update:WSL:Update:CR):"
osc -A https://api.suse.de ls -b SUSE:SLE-$VERSION:Update:WSL:Update:CR/wsl-appx/standard | grep "\.appx$" | sed -e 's/^[[:space:]]*//'

